<?php


class TextItalicStrong extends TextStrong
{
    public function getValue(): string
    {
        return sprintf('<em>%s</em>',
            parent::getValue() // TODO: Change the autogenerated stub

        );
    }
}