<?php


class TextStrongItalic extends TextStrong
{
    public function getValue(): string
    {
        return sprintf('<strong><em>%s</em></strong>',
            parent::getValue() // TODO: Change the autogenerated stub

        );
    }
}